#!/usr/bin/make
#
# plone-path is added when "vhost_path: mount/site" is defined in puppet
plone=$(shell grep plone-path port.cfg|cut -c 14-)
hostname=$(shell hostname)
instance1_port=$(shell grep instance1-http port.cfg|cut -c 18-)

all: run

.PHONY: bootstrap
bootstrap:
	virtualenv-2.7 .
	./bin/python bootstrap.py -v 2.2.5

.PHONY: buildout
buildout:
	if ! test -f bin/buildout;then make bootstrap;fi
	if ! test -f var/filestorage/Data.fs;then make standard-config; else bin/buildout -v;fi

.PHONY: upgrade
upgrade:
	if ! test -f bin/instance1;then make buildout;fi
	echo $(plone)
	echo $(hostname)
	echo $(instance1_port)
	# copy-data is generated by puppet when data_source is found
	./copy-data.sh --disable-auth=1
	./bin/upgrade-portals --username admin -G profile-imio.dms.mail:default $(plone)
	$ echo "Upgrade done for instance $(plone), check http://$(hostname):$(instance1_port)/manage_main" | mail -s "Migration finished for $(plone)" stephan.geulette@imio.be

.PHONY: standard-config
standard-config:
	if ! test -f bin/buildout;then make bootstrap;fi
	bin/buildout -vt 5 -c standard-config.cfg

.PHONY: run
run:
	if ! test -f bin/instance1;then make buildout;fi
	bin/instance1 fg

.PHONY: robot-server
robot-server:
	bin/robot-server -v imio.dms.mail.testing.DMSMAIL_ROBOT_TESTING

.PHONY: doc
doc:
	# can be run by example with: make doc opt='-t "Contacts *"'
	bin/robot $(opt) src/imio.dms.mail/imio/dms/mail/tests/robot/doc.robot

.PHONY: coverage
coverage:
	bin/coverage
	bin/coverageme

.PHONY: cleanall
cleanall:
	rm -fr lib bin/buildout develop-eggs downloads eggs parts .installed.cfg
