# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 2.7
      uses: actions/setup-python@v3
      with:
        python-version: "2.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        virtualenv .
        ./bin/pip install -r https://dist.plone.org/release/4.3.20/requirements.txt
        ./bin/buildout
    - name: Test
      run: |
        ./bin/testme
